### ISSUE TITLE
IDF?

### ISSUE THREAD

**Issue by nagyrobi** [kecajtop/dtr0xx_io#13]
In the readme the example contains
```yaml
esp32:
  board: esp32dev
  framework:
    type: arduino
```

Could there be any potential issue if we could use `type: esp-idf` instead of `arduino`?
